#!/usr/bin/env bash
# install --- install the iterm2 preferences custom folder and plist

# Mike Barker <mike@thebarkers.com>
# December 18th, 2016

ITERM2_DST_DIR=${HOME}/.iterm2
ITERM2_SRC_DIR=${HOME}/src/dot-iterm2
ITERM2_PREFERENCES=com.googlecode.iterm2.plist
ITERM2_IMGCAT_URL=https://iterm2.com/imgcat
ITERM2_IT2DL_URL=https://iterm2.com/it2dl

mkdir -p ${ITERM2_DST_DIR}

if [ -f "${ITERM_DST_DIR}/${ITERM2_PREFERENCES}" ] && \
    [ ! -L "${ITERM_DST_DIR}/${ITERM2_PREFERENCES}" ]; then
    mv ${ITERM_DST_DIR} ${ITERM2_DST_DIR}.bak
fi

ln -fs ${ITERM2_SRC_DIR}/${ITERM2_PREFERENCES} ${ITERM2_DST_DIR}/${ITERM2_PREFERENCES}

curl -L https://iterm2.com/misc/$(basename $SHELL)_startup.in \
    -o ${HOME}/.iterm2/iterm2_shell_integration.$(basename $SHELL)

curl -L ${ITERM2_IMGCAT_URL} -o ${HOME}/.iterm2/imgcat
chmod +x ${HOME}/.iterm2/imgcat

curl -L ${ITERM2_IT2DL_URL} -o ${HOME}/.iterm2/it2dl
chmod +x ${HOME}/.iterm2/it2dl
