#!/usr/bin/env bash
# upgrade_shell_integration --- download the latest shell integration script

# Mike Barker <mike@thebarkers.com>
# October 3rd 2017

DIR="$(cd "$(dirname "$0")" && pwd)"

DST_DIR=${HOME}/.iterm2
ITERM2_URL=https://iterm2.com

# Define utility programs to be installed
UTILS[0]="divider"
UTILS_URL[0]="https://raw.githubusercontent.com/gnachman/iTerm2/master/tests/divider"
UTILS[1]="imgcat"
UTILS_URL[2]="https://iterm2.com/utilities/${UTILS[1]}"
UTILS[2]="imgls"
UTILS_URL[2]="https://iterm2.com/utilities/${UTILS[2]}"
UTILS[3]="it2attention"
UTILS_URL[3]="https://iterm2.com/utilities/${UTILS[3]}"
UTILS[4]="it2check"
UTILS_URL[4]="https://iterm2.com/utilities/${UTILS[4]}"
UTILS[5]="it2copy"
UTILS_URL[5]="https://iterm2.com/utilities/${UTILS[5]}"
UTILS[6]="it2dl"
UTILS_URL[6]="https://iterm2.com/utilities/${UTILS[6]}"
UTILS[7]="it2getvar"
UTILS_URL[7]="https://iterm2.com/utilities/${UTILS[7]}"
UTILS[8]="it2setcolor"
UTILS_URL[8]="https://iterm2.com/utilities/${UTILS[8]}"
UTILS[9]="it2setkeylabel"
UTILS_URL[9]="https://iterm2.com/utilities/${UTILS[9]}"
UTILS[10]="it2ul"
UTILS_URL[10]="https://iterm2.com/utilities/${UTILS[10]}"
UTILS[11]="it2universion"
UTILS_URL[11]="https://iterm2.com/utilities/${UTILS[11]}"

echo
echo "Download iterm2 shell utilities"
for idx in ${!UTILS[*]}; do
	file=${UTILS[$idx]}
	url=${UTILS_URL[$idx]}
	echo
	echo "... downloading file: $url"
	curl -L ${url} -o ${DST_DIR}/$file
	chmod +x ${DST_DIR}/$file
done
